# Generated by Django 5.1.2 on 2024-10-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_x_wow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipments_checksum',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
