# Generated by Django 5.1.2 on 2024-10-19 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_x_wow', '0002_character_equipments_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dps_score', models.IntegerField()),
                ('rating_time', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_x_wow.character')),
            ],
        ),
    ]
