services:
  server:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn djangofun.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.prod.env
    depends_on:
      - db
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/server/staticfiles
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp/simc:/tmp/simc
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.prod.db.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - static_volume:/home/app/server/staticfiles

volumes:
  postgres_data:
  static_volume:
